---
apiVersion: v1
kind: Pod
metadata:
 name: kubesmoke-prometheus
 labels:
   app: kubesmoke
spec:
 containers:

   - name: incr
     image: zilman/kubesmoke-prom
     command: ["python", "/tests/incr.py"]
     ports:
     - containerPort: 8000

   - name: status
     image: zilman/kubesmoke-prom
     command: ["python", "/tests/status.py"]
